apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: model-{{  experiment_id }}
spec:
  annotations:
    project_name: {{  model_name }}
    deployment_version: {{  experiment_id }}
  #     seldon.io/engine-separate-pod: "true"
  name: {{  model_name }}
  predictors:
    - componentSpecs:
        - hpaSpec:
            maxReplicas: 5
            metrics:
              - resource:
                  name: cpu
                  targetAverageUtilization: 5
                type: Resource
            minReplicas: 1
          spec:
            containers:
              - image: "image-registry.openshift-image-registry.svc:5000/{{project}}/{{image_name}}"
                imagePullPolicy: Always
                name: {{  model_name }}
                env:
                  - name: MODEL_NAME
                    value: {{  model_name }}
                  - name: SERVICE_TYPE
                    value: MODEL
                  - name: GRPC_PORT
                    value: "5005"
                  - name: METRICS_PORT
                    value: "6005"
                  - name: HTTP_PORT
                    value: "9000"


      graph:
        name: {{  model_name }}
        endpoint:
          type: REST
          service_host: localhost
          service_port: 9000
        type: MODEL
      name: {{  model_name }}
      annotations:
        predictor_version: {{  experiment_id }}
        team: opendatahub
      #         seldon.io/svc-name: "EXPERIMENT_ID"
      labels:
        team: opendatahub
        version: predictor

      replicas: 1
